### ISSUE TITLE
UnboundLocalError: local variable 'volume' referenced before assignment

### ISSUE THREAD

**Issue by camlloyd** [camlloyd/oct-to-tiff#39]
### Discussed in https://github.com/camlloyd/oct-to-tiff/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **Frankieljy** January  2, 2023</sup>
I meet this problem when i try following:
`oct-to-tiff /home/0808/datasets/Testdataset16.49.05_1.OCT
`
can you share some suggestions?</div>

**Comment by camlloyd** [comment]
> ### Discussed in #38
> 
> Originally posted by **Frankieljy** January 2, 2023 I meet this problem when i try following: `oct-to-tiff /home/0808/datasets/Testdataset16.49.05_1.OCT ` can you share some suggestions?

Hi @Frankieljy, this error occurs as `oct-to-tiff` expects one of the [supported scan patterns](https://github.com/camlloyd/oct-to-tiff#supported-scan-patterns) to be present in the filename. 

Do you know which scan pattern `Testdataset16.49.05_1.OCT`should be?
- If yes, try adding this to the filename (e.g. `oct-to-tiff "/home/0808/datasets/3D Cornea Testdataset16.49.05_1.OCT"`
- If no, are you able to send me any test data?

Do you have lots of files named in this way, and is there a reason for this?

Thanks.

**Comment by Frankieljy** [comment]
Thanks for you soon replay,This file name is not in a standard format.The format of the dataset I get is as follows:
--lu, jiayi12.16 _112_HD Angio Retina_OD_2022-12-16_16.51.33_1.OCT
--lu, jiayi12.16 _112_HD Angio Retina_OD_2022-12-16_16.51.33_1.txt
--lu, jiayi12.16 _112_HD Angio Retina_OD_2022-12-16_16.51.33_1.bmp

After your valuable suggestions, I tried the following methods, but could not identify them:

oct-to-tiff "HD Angio Retina OD_2022-12-16_16.51.33_1.OCT"
oct-to-tiff "HD Angio Retina OD_2022-12-16_16.51.33_1.OCT" --angio --size 6
But the second show the following wrong:
cannot reshape array of size 204800000 into shape(1131,1131,160)
Our file name already contains HD Angio Retina, and l search the code find the shape is like 400 400 640
But the first instruction can be successfully converted to .ometif and l use QuPath can see the image.
This is really a great project.
An example data we collected this time is given in the attachment, and we hope to give us some more suggestions
Thanks













At 2023-01-03 05:03:43, "Cameron Lloyd" ***@***.***> wrote:

Discussed in #38

Originally posted by Frankieljy January 2, 2023 I meet this problem when i try following: oct-to-tiff /home/0808/datasets/Testdataset16.49.05_1.OCT can you share some suggestions?

Hi @Frankieljy, this error occurs as oct-to-tiff expects one of the supported scan patterns to be present in the filename.

Do you know which scan pattern Testdataset16.49.05_1.OCTshould be?

If yes, try adding this to the filename (e.g. oct-to-tiff "/home/0808/datasets/3D Cornea Testdataset16.49.05_1.OCT"
If no, are you able to send me any test data?

Do you have lots of files named in this way, and is there a reason for this?

Thanks.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
mou, lei _119_HD Angio Retina_OD_2022-12-18_18.59.15_1.OCT (390.63M, 2023年1月18日 21:07 到期)
下载
mou, lei _119_HD Angio Retina_OD_2022-12-18_18.59.15_1.txt (766B, 2023年1月18日 21:07 到期)
在线预览 | 下载

**Comment by camlloyd** [comment]
Hi @Frankieljy,

You should not need to rename any files, and you do not need to pass `--angio` or `--size` arguments for an `.OCT` file.

`oct-to-tiff "lu, jiayi12.16 _112_HD Angio Retina_OD_2022-12-16_16.51.33_1.OCT"` should convert succesfully.

Unfortunately, it's not possible to attach files here using email reply.

Thanks.

**Comment by Frankieljy** [comment]
Hi @camlloyd 
Here is the attachment mentioned in the previous email:
https://drive.google.com/file/d/1KC7aQ99lQk5dEeZnKU5PkytYen7IEc-5/view?usp=share_link
We now have a small question, that is, whether the current file can identify the blood vessel information in it and turn it into an OCTA three-dimensional image.
Please give us some suggestions.
Thanks!!!!

**Comment by camlloyd** [comment]
@Frankieljy I requested access.

See https://github.com/camlloyd/oct-to-tiff/issues/17.

**Comment by Frankieljy** [comment]
Sorry for reply later. It took me some time to try to export dataset.
As OCTA data is stored in these folders as .images files,I export one of the data,but it only have 20MB and can't be use.I try the following:
**oct-to-tiff "xxx.images" --angio --size 6**
and thre result is:
line 17, in convert oct file volume = np.frombuffer(f.read(), dtype=np.uint16)
**ValueError: buffer size must be a multiple of element size**
Maybe some license is missing ?
**Our RTVue XR information:**
software version:Version 2018.1.1.63
Feature upgraded:AngioVue Analytics,AngioVue
All Activated Licenses:
FEATURE LICENSES
AngioVue
AngioVue Analytics
the data we output is here:
https://drive.google.com/file/d/1nRX4eo7rr0dNozbV80Q4i2-D3a8ufHoY/view?usp=share_link

**Comment by camlloyd** [comment]
Hi @Frankieljy,

I can convert your data succesfully.

You missed this step:

> ```
> $ binwalk -e /DiagnosisData/.images
> ```

Good luck!

**Comment by Frankieljy** [comment]
Thanks for your reply!!!
I will try it

**Comment by Frankieljy** [comment]
This is an amazing project. We still have two questions. Please answer them when you are free.

**First**:The whole data structure looks like this:
├── DiagnosisData
│   ├── 3a
│   │   ├── 3a1e31e410ffd344aff68b30f7e29ac3
│   │   └── 3a1e31e410ffd344aff68b30f7e29ac3.images
│   ├── 40
│   │   ├── 40f538e2c2ff3549952841726ac8b2f4
│   │   └── 40f538e2c2ff3549952841726ac8b2f4.images
│   ├── a3
│   │   ├── a3ca2ba05b6bf14393cd34c6cedd55aa
│   │   └── a3ca2ba05b6bf14393cd34c6cedd55aa.images
│   ├── b7
│   │   ├── b7102debeccb9641a81cd1366d087611
│   │   └── b7102debeccb9641a81cd1366d087611.images
│   ├── bd
│   │   ├── bd1ccbc8b19bff44a8aa95b636bbcb58
│   │   └── bd1ccbc8b19bff44a8aa95b636bbcb58.images
│   └── f9
│       ├── f9887fca11668b4d88bedaa05be376af
│       └── f9887fca11668b4d88bedaa05be376af.images
├── OutputDB.bak
└── RawData
    ├── 3a
    │   └── 3a1e31e410ffd344aff68b30f7e29ac3
    ├── 40
    │   └── 40f538e2c2ff3549952841726ac8b2f4
    ├── a3
    │   └── a3ca2ba05b6bf14393cd34c6cedd55aa
    ├── b7
    │   └── b7102debeccb9641a81cd1366d087611
    ├── bd
    │   └── bd1ccbc8b19bff44a8aa95b636bbcb58
    └── f9
        └── f9887fca11668b4d88bedaa05be376af
the data in raw data flod is about 513MB,we are wondering whether some useful information is stored in it and can be converted.

**Second**:we also want to try the **--en-face**: convert extracted en face data.Bur we have no idea about what kind of 
`/path/to/data` can be use,we try the data use for oct convert(*.OCT) ,the data (*.images)and the data after use binwalk,but all of them can't get the result.So ,what kind of data can be use for this command?
Here is the [rawdata](https://drive.google.com/drive/folders/1MX4z7158C6w4La0Xo4ANsC8l2A7L2uqz?usp=share_link) we mention above:

**Comment by camlloyd** [comment]
Thank you @Frankieljy!

`--en-face` is still experimental and requires carving out the data manually from the `.images` file first.
This data contains OCT en face slabs at predefined layers. 
Can you give me upload permission?

**Comment by Frankieljy** [comment]
Thanks for your soon reply!

> Can you give me upload permission?
What platform will the data be uploaded to? We want to know the general information of this platform.

**Comment by camlloyd** [comment]
> Thanks for your soon reply!
> 
> > Can you give me upload permission?
> 
> What platform will the data be uploaded to? We want to know the general information of this platform.

Your Google Drive folder above.

**Comment by Frankieljy** [comment]
the [raw data](https://drive.google.com/drive/folders/1MX4z7158C6w4La0Xo4ANsC8l2A7L2uqz?usp=sharing) fold permission is open,thanks for your soon reply

**Comment by camlloyd** [comment]
Done. Please close the folder.

**Comment by Frankieljy** [comment]
Thanks for your great work.
I have close the folder.And we still have a question:
As is shown in the images , all of them have some stripe.We think this may casuse from the eyeball tremble when we shot?
And if possible,we want to see another` .images` en face ,here is the [data](https://drive.google.com/drive/folders/1zEaN7aBWnFO6sLug4Z74r7FFnaxUFB3f?usp=sharing). 

Best Regard!

**Comment by camlloyd** [comment]
Yes, could you upload another `.images` file please?

**Comment by Frankieljy** [comment]
here is the [data source](https://drive.google.com/drive/folders/1zEaN7aBWnFO6sLug4Z74r7FFnaxUFB3f?usp=share_link)

**Comment by camlloyd** [comment]
These look different compared to the first file, are there any more available?

**Comment by Frankieljy** [comment]
Sorry for reply later
It takes sometime to apply for more data,here has four` .images` datas in the [fold](https://drive.google.com/drive/folders/1zEaN7aBWnFO6sLug4Z74r7FFnaxUFB3f?usp=share_link),you can try them when you are free.
Best Regard!

**Comment by camlloyd** [comment]
Hi @Frankieljy, please see the folder.

I will be closing this issue now.
